### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by KiExitDispatcher** [anti-captcha/anticaptcha-npm#2]
Will yall add golang by anytime? it would be realy nice.

**Comment by anti-captcha** [comment]
Hi, you can use this one from our customer https://github.com/nuveo/anticaptcha

**Comment by KiExitDispatcher** [comment]
Hi, ill be making custom one that one is old.

**Comment by anti-captcha** [comment]
Great, get a soft_id here and add to your createTask requests to earn commission 
https://anti-captcha.com/clients/tools/devcenter

**Comment by KiExitDispatcher** [comment]
no worries. my friend took care of the api key.

**Comment by KiExitDispatcher** [comment]
![image](https://github.com/anti-captcha/anticaptcha-npm/assets/151552809/02b934f4-8c55-4b9f-a2a3-234a27d3ddb0)
![image](https://github.com/anti-captcha/anticaptcha-npm/assets/151552809/059734d7-a52c-4bf4-8897-ca97099496aa)
currently working on it 👍
